### PR TITLE
Whitelist files that are released on npm and Bower

### LINKED ISSUE #30: Published packages are bloated
The npm and Bower packages are bloated being recognition. We should whitelist the files that are needed in production so that people get only those when they install the packages.

### PR DESCRIPTION
**Pull request by sindrenm**
Fixes #30.

As far as I know, there is no standard way of whitelisting in Bower, you'd have to blacklist everything and then negate that for the items you want to include. So I did that. npm has a whitelisting feature. So I used that too.

### CODE REVIEW

**Comment by sindrenm** [comment]
Perhaps it is a good idea to release this one right away (after merge, of course) as v1.0.1, as the packages in npm and Bower right now are quite bloated. What do you think?

**Comment by sindrenm** [comment]
Actually, there are multiple things that needs fixing. Let's wait a bit with v1.0.1. I'll make a milestone and some issues.

**Comment by timkurvers** [comment]
@sindrenm This should be good to go for tweakage now.

**Comment by sindrenm** [comment]
Tweakage has to be the greatest word ever! I'll merge master in here. :smiley:

**Comment by timkurvers** [comment]
Do we want to include LICENSE and README in the distribution? I think at least npm will include README (if any) by default.

**Comment by sindrenm** [comment]
That's a good point. I'll add them both, probably a good idea. :smiley:

**Comment by sindrenm** [comment]
@timkurvers: There. :smiley:

**Comment by timkurvers** [comment]
Great stuff! :cake:

**Comment by sindrenm** [comment]
Thanks! :facepunch:

**Pull request merged**
