### PR TITLE
Change README to include module import

### PR DESCRIPTION
**Pull request by zebulgar**

### CODE REVIEW

**Comment by jgorset** [comment]
Thanks, @MITDelian! I feel it's a better fit under "Installation", though — "Usage" is just meant to give you an idea of what it's like to use when you're all set. I'll merge this and make the change.

**Comment by jgorset** [comment]
:sparkles: :cake: :sparkles:

**Comment by jgorset** [comment]
Moved in 9b3547bd8acc42f644eec92811f497b4e57e612b

**Comment by sindrenm** [comment]
This is great, thanks!

**Pull request merged**
