### PR TITLE
Annotate dist file with array syntax DI

### LINKED ISSUE #36: Build dist files with array-style DI

### PR DESCRIPTION
**Pull request by sindrenm**
Fixes #36.

### CODE REVIEW

**Comment by sindrenm** [comment]
Let me have a look to see if there's a way to force single quotes from ng-annotate to keep it consistent with the rest.

**Comment by sindrenm** [comment]
I have no idea why the PR build fails on Travis, btw. Seems like the karma-browserify package won't install due to a checksum mismatch:

> ```
> npm ERR! shasum check failed for /tmp/npm-2071-cfd09410/registry.npmjs.org/karma-browserify/-/karma-browserify-4.1.1.tgz
> npm ERR! Expected: fe3e43f2eab1934ee08dc47a89575d52cb0bb77b
> npm ERR! Actual:   0a9fc7dc0e9aca0d4346067a2e61aee57afdadf1
> npm ERR! From:     https://registry.npmjs.org/karma-browserify/-/karma-browserify-4.1.1.tgz
> ```

**Comment by sindrenm** [comment]
So, while it didn't work to re-run the build on Travis, a new build with different code seems to make the build go green again. :smiley:

**Comment by jgorset** [comment]
So this is so the module won't break under production environments in frameworks that minify assets, right?

**Comment by jgorset** [comment]
If so, I like it a lot. Otherwise I probably also like it.

**Comment by sindrenm** [comment]
Yes, correct! And it's quite necessary. :wink:

**Pull request merged**
